import type { Metadata } from "next";
import "./globals.css";
import Main from "@/components/Main";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by sellit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-mono antialiased min-h-screen bg-cover bg-center`}
        style={{
          backgroundImage: "url('/pttern.jpg')",
        }}
      >
        <Main>
        {children}
        </Main>
      </body>
    </html>
  );
}
